server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true           # 프로덕션은 true 권장
        same-site: lax         # 브라우저 기본 동작과 호환

spring:
  jackson:
    default-property-inclusion: non_null
  mvc:
    problemdetails:
      enabled: true
